# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: deps:ruby:.
version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: Run tests
          command: xcodebuild -workspace QuizApp.xcworkspace -sceme CI -destination 'platform=iOS Simulator,OS=17.2,name=iPhone 15 Pro' build
  build:
    macos:
      xcode: "15.2.0"
    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Build an artifact
          command: xcodebuild -workspace QuizApp.xcworkspace -sceme QuizApp -destination 'platform=iOS Simulator,OS=17.2,name=iPhone 15 Pro' build
      - store_artifacts:
          path: example.txt
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
workflows:
   version: 2
  build_and_test:
    jobs:
      - build
